version: "3.6"
services:
  server:
    build:
        context: ../heos-api-server
        dockerfile: Dockerfile
    environment:
      - CONF_PLAYER_NAME=Denon AVR-X2700H
      - CONF_USER=fake@gmail.com
      - CONF_PW=do-not-use-qwerty-as-your-password
    network_mode: host
  remote-control:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8000:80